apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shirodkar/helm.git'
    path: cicd
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cicd
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
