apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
spec:
  project: default
  source:
    repoURL: 'https://github.com/stakater/Reloader.git'
    path: deployments/kubernetes/chart/reloader
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
