apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-one
  namespace: {{ .Values.destination.namespace }}
spec:
  project: default
  source:
    repoURL: 'https://github.com/shirodkar/helm.git'
    path: service-one
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.destination.namespace }}