kind: Secret
apiVersion: v1
metadata:
  name: quayio
data:
  config.json: ewoJImF1dGhzIjogewoJCSJxdWF5LmlvIjogewoJCQkiYXV0aCI6ICJjbWhmWldWZmMzTm9hWEp2WkdzNmNtaGZaV1ZmYzNOb2FYSnZaR3M9IgoJCX0KCX0KfQ==
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: my-basic-auth-secret
data:
  .git-credentials: aHR0cHM6Ly9zaGlyb2RrYXI6Z2hwX3JQdDhFeXlrNExCV21JdGVNM0haU214YzcwVnBmejF6d0pKT0BnaXRodWIuY29tCg==
  .gitconfig: W2NyZWRlbnRpYWwgImh0dHBzOi8vZ2l0aHViLmNvbSJdCiAgaGVscGVyID0gc3RvcmUK
type: Opaque
