kind: Secret
apiVersion: v1
metadata:
  name: quaysecret
data:
  config.json: {{ .Values.dockerconfigjson }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: github-secret
data:
  .git-credentials: {{ .Values.gitcredentials }}
  .gitconfig: {{ .Values.gitconfig}}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: quayio
  annotations:
    tekton.dev/docker-0: 'https://quay.io/'
data:
  .dockerconfigjson: {{ .Values.quaycredentials }}
type: kubernetes.io/dockerconfigjson

