kind: Secret
apiVersion: v1
metadata:
  name: quaysecret
data:
  config.json: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJleGFtcGxlLXJlZ2lzdHJ5LXF1YXktb3BlbnNoaWZ0LW9wZXJhdG9ycy5hcHBzLnJvc2EtNXh3ZDQueGJtby5wMS5vcGVuc2hpZnRhcHBzLmNvbSI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiYzJocGNtOWthMkZ5T25Ob2FYSnZaR3RoY2c9PSIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAicXVheS5pbyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiY21oZlpXVmZjM05vYVhKdlpHczZjbWhmWldWZmMzTm9hWEp2WkdzPSIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAicmVnaXN0cnkucmVkaGF0LmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJjMmhwY205a2EyRnlMbk5oWTJocGJrQm5iV0ZwYkM1amIyMDZjbXRuYTBFM2VIcGxaQ0U9IgogICAgICAgICAgICAgICAgfQogICAgICAgIH0KfQ==
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: github-secret
data:
  .git-credentials: aHR0cHM6Ly9zaGlyb2RrYXI6Z2hwX3JQdDhFeXlrNExCV21JdGVNM0haU214YzcwVnBmejF6d0pKT0BnaXRodWIuY29tCg==
  .gitconfig: W2NyZWRlbnRpYWwgImh0dHBzOi8vZ2l0aHViLmNvbSJdCiAgaGVscGVyID0gc3RvcmUK
type: Opaque
