kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-two
  template:
    metadata:
      labels:
        app: service-two
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: service-two
          image: '{{ .Values.registry }}/demo-service-two:{{ .Values.image.tag }}'
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: service-two-config
      imagePullSecrets:
        - name: quayio
  strategy:
    type: RollingUpdate
