apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  database-name: {{ .Values.database.name }}
  database-password: {{ .Values.database.password }}
  database-user: {{ .Values.database.user }}
