apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: service-one
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        finalizers:
          - chains.tekton.dev/pipelinerun
        labels:
          tekton.dev/pipeline: service-one
        name: service-one-$(uid)
      spec:
        pipelineRef:
          name: service-one
        taskRunTemplate:
          serviceAccountName: pipeline
        timeouts:
          pipeline: 1h0m0s
        workspaces:
          - name: app
            persistentVolumeClaim:
              claimName: service-one
          - name: quaysecret
            secret:
              secretName: quaysecret
          - name: gitops
            persistentVolumeClaim:
              claimName: gitops
          - name: githubsecret
            secret:
              secretName: github-secret
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: service-two
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        finalizers:
          - chains.tekton.dev/pipelinerun
        labels:
          tekton.dev/pipeline: service-two
        name: service-two-$(uid)
      spec:
        pipelineRef:
          name: service-two
        taskRunTemplate:
          serviceAccountName: pipeline
        timeouts:
          pipeline: 1h0m0s
        workspaces:
          - name: app
            persistentVolumeClaim:
              claimName: service-two
          - name: quaysecret
            secret:
              secretName: quaysecret
          - name: gitops
            persistentVolumeClaim:
              claimName: gitops
          - name: githubsecret
            secret:
              secretName: github-secret
